// src/views/CriteriaView.tsx
import { CriteriaCard } from '@/components/DealRoom/CriteriaCard';
import { useCriteria, useDealRoom } from '@/context/DealRoomContext';

export function CriteriaView() {
  const service = useDealRoom();
  const criteria = useCriteria();

  const handleCriteriaChange = (e: any) => {
    service.send({
      type: 'UPDATE_CRITERIA',
      criteria: { [e.target.name]: e.target.value }
    });
  };

  return (
    <div className="container mx-auto p-4">
      <CriteriaCard
        criteria={criteria}
        onCriteriaChange={handleCriteriaChange}
      />
    </div>
  );
}

// src/views/CriteriaView.vue
`<template>
  <div class="container mx-auto p-4">
    <CriteriaCard
      :criteria="criteria"
      @criteria-change="handleCriteriaChange"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { CriteriaCard } from '@/components/DealRoom/CriteriaCard.vue';
import { useDealRoomStore } from '@/stores/dealRoom';

const store = useDealRoomStore();
const criteria = computed(() => store.criteria);

const handleCriteriaChange = (e: any) => {
  store.updateCriteria({ [e.target.name]: e.target.value });
};
</script>`
