// src/views/UploadView.tsx
import { BatchUploadZone } from '@/components/DealRoom/BatchUploadZone';
import { useDealRoom } from '@/context/DealRoomContext';

export function UploadView() {
  const service = useDealRoom();
  const isUploading = service.state.matches('analyzing');

  const handleFilesAccepted = async (files: File[]) => {
    service.send({ type: 'UPLOAD_DOCUMENTS', documents: files });
  };

  return (
    <div className="container mx-auto p-4">
      <BatchUploadZone
        onFilesAccepted={handleFilesAccepted}
        isUploading={isUploading}
      />
    </div>
  );
}

// src/views/UploadView.vue
<template>
  <div class="container mx-auto p-4">
    <BatchUploadZone
      :is-uploading="isUploading"
      @files-accepted="handleFilesAccepted"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import BatchUploadZone from '@/components/DealRoom/BatchUploadZone.vue';
import { useDealRoomStore } from '@/stores/dealRoom';

const store = useDealRoomStore();
const isUploading = computed(() => store.isAnalyzing);

const handleFilesAccepted = async (files: File[]) => {
  await store.uploadDocuments(files);
};
</script>
